import "./globals.css";
import { Nunito_Sans } from "next/font/google";
import Header from "@/components/Header/Header";
const nunitoSans = Nunito_Sans({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Joshua Caleb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={nunitoSans.className}>
      <head>
        <link rel="icon" href="/branding/logo.png" />
      </head>
      <body
        className="m-auto min-h-screen max-w-screen-xl scroll-smooth bg-gradient-to-tr 
		from-[#FFFFFF] to-[#969CB2] bg-no-repeat px-4 pt-2"
      >
        <Header />
        <main className="m-auto">{children}</main>
      </body>
    </html>
  );
}
